---
- name: Start docker service
  service: name=docker state=started

- name: Add azk apt key
  apt_key: keyserver="{{ azk_keyserver }}" id="{{ azk_keyid }}"

- name: Add azk repo
  apt_repository: repo="{{ azk_repo }}" state=present

- name: Install packages
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
  - azk
  - git
  - iptables-persistent
