---
- hosts: all
  sudo: true
  tasks:
    - name: Copy .env to server
      copy:
        src={{ local_project_path }}/{{ env_file }}
        dest={{ remote_project_path }}/.env
        owner={{ user }}
        mode=0600
