---
- hosts: all
  vars:
    azk_start_path: "/home/{{ user }}/bin/azk-start"
    list_versions_command: "git tag -n | tac"
  tasks:
    - name: Check azk-start script
      stat: path={{ azk_start_path }}
      when: op is not defined or op == "rollback"

    - name: Restore previous version
      shell: "{{ azk_start_path }} {{ git_ref }} > {{ output_file }} 2>&1"
      become: yes
      become_user: "{{ user }}"
      when: op is not defined or op == "rollback"

    - name: List available versions
      shell: "{{ list_versions_command }} > {{ output_file }} 2>&1"
      args:
        chdir: "{{ git_dir }}"
      become: yes
      become_user: "{{ user }}"
      when: op is defined and op == "list"
